typography_spectrum: 1
color:
  brandColors:
    - '#cc0325'
    - '#9d9d9d'
    - '#616161'
    - '#ffffff'
    - '#cdcdcd'
  brandStrength: 0.5625
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.09372
analytics:
  google: null
  facebook: null
  twitter: null
name: 'Peak Performance Communication '
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Peak Performance Communication Training
purpose: []
