name: DDC Communications
favicon: null
layout_spectrum: 1
typography_spectrum: 0.86584
title: Peak Performance Communication Training
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#595959'
    - '#ffab41'
    - '#cc0001'
    - '#0197a6'
    - '#fdfdfd'
  brandStrength: 0.8418547
  lightness: 0.5625
  saturation: 0.5971282
  rhythmicContrast: 0.5
purpose: []
