typography_spectrum: 1
style: the-composer
color:
  brandColors:
    - '#cc0325'
    - '#9d9d9d'
    - '#616161'
    - '#ffffff'
    - '#cdcdcd'
  brandStrength: 0.5625
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.09372
analytics:
  google: null
  facebook: null
  twitter: null
name: 'Peak Performance Communication '
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Contact Us
    id: 8a2bf6be-5c8a-44d8-b407-5e8ab753a343
    type: content
  - name: Video
    url: 'https://vimeo.com/158047492'
    type: external
favicon: null
title: Peak Performance Communication Training
purpose: []
