name: DDC Communications
favicon: null
layout_spectrum: 1
typography_spectrum: 0.86584
title: Peak Performance Communication Training
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cc0325'
    - '#fefefe'
    - '#040000'
    - '#c34a5c'
    - '#474344'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
