name: DDC Communications
favicon: null
layout_spectrum: 0.24338
typography_spectrum: 1
title: Peak Performance Communication Training
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cc0325'
    - '#9d9d9d'
    - '#616161'
    - '#ffffff'
    - '#cdcdcd'
  brandStrength: 0.5625
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
