typography_spectrum: 0.17581443046219647
color:
  brandColors:
    - '#595241'
    - '#B8AE9C'
    - '#FFFFFF'
    - '#ACCFCC'
    - '#8A0917'
  brandStrength: 0.39739402779377997
  lightness: 1
  saturation: 0.4706476894207299
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4759517970960587
analytics:
  google: UA-83378128-1
  facebook: null
  twitter: null
name: 'Peak Performance Communication '
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Contact Us
    id: 8a2bf6be-5c8a-44d8-b407-5e8ab753a343
    type: content
favicon: null
title: Peak Performance Communication Training
purpose: []
